mysite/accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

mysite/articles/urls.py
from django.urls import path
from articles import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name="articles"),
    path('create', views.article_create, name='create'),
    path('<slug:slug>', views.article_item, name='article-detail'),
    path('update/<slug:slug>/', views.article_update, name='update'),
    path('delete/<slug:slug>/', views.article_delete, name='delete'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mysite import views
from articles import views as article_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', article_views.article_list, name="homepage"),
    path('about/', views.about, name="about"),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/accounts/models.py
from django.db import models

# Create your models here.

mysite/articles/models.py
from django.contrib.auth.models import User
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumbnail = models.ImageField(upload_to='images/', blank=True, default='images/default.png')
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    def snippet(self):
        return self.body[0:50] + '...'

mysite/accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm
from django.contrib.auth import password_validation

class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={"autofocus": True, "class": "form-control mb-3"}))
    password = forms.CharField(
        label = "Password",
        strip = False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password", "class": "form-control mb-3"}),
    )

class SignupForm(UserCreationForm):
    username = UsernameField(widget=forms.TextInput(attrs={"autofocus": True, "class": "form-control mb-3"}))
    password1 = forms.CharField(
        label = "Password",
        required = True,
        strip = False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", "class": "form-control mb-3"}),
        help_text=password_validation.password_validators_help_text_html()
    )
    password2 = forms.CharField(
        label = "Password confirmation",
        required = True,
        strip = False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", "class": "form-control mb-3"}),
        help_text = "Enter the same password as before, for verification",
    )

mysite/articles/forms.py
from django import forms
from . import models

class ArticleForm(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'thumbnail']
        labels = {
            "title": "Title",
            "body": "Text",
            "thumbnail": "Thumbnail"
        }
        widgets = {
            "title": forms.TextInput(attrs={'placeholder': 'Write article title', 'class': 'form-control mb-3'}),
            "body": forms.TextInput(attrs={'placeholder': 'Write article text', 'class': 'form-control mb-3'}),
            "thumbnail": forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

mysite/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.http import HttpResponseRedirect

from accounts.forms import LoginForm, SignupForm

def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return HttpResponseRedirect('/articles')
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return redirect('articles:articles')
    else:
        form = LoginForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
    return HttpResponseRedirect('/articles')

mysite/articles/views.py
from django.contrib.auth.decorators import login_required
from . import forms
from django.shortcuts import render, redirect
from articles.models import Article
from django.http import HttpResponse

def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': articles})

def article_item(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_item.html', {'article': article})

@login_required(login_url='accounts:login')
def article_create(request):
    if request.method == 'POST':
        form = forms.ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('homepage')
    else:
        form = forms.ArticleForm()
    return render(request, 'articles/article_form.html', {'form': form})

@login_required(login_url='accounts:login')
def article_update(request, slug):
    article = Article.objects.get(slug=slug)
    if request.user.id == article.author.id:
        if request.method == 'POST':
            form = forms.ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.author = request.user
                instance.save()
                return redirect('articles:article-detail', slug=article.slug)
        else:
            form = forms.ArticleForm(instance=article)
        
        return render(request, 'articles/article_form.html', {'form': form})
    return HttpResponse('401 Unauthorized', status=401)
            
@login_required(login_url='accounts:login')
def article_delete(request, slug):
    article = Article.objects.get(slug=slug)
    if request.user.id == article.author.id:
        if request.method == 'POST':
            article.delete()
            return redirect('homepage')
        return render(request, 'articles/article_confirm_delete.html', {'article': article})
    return HttpResponse('401 Unauthorized', status=401)

mysite/mysite/views.py
from django.http import HttpResponse
from django.shortcuts import render
from articles.models import Article

def homepage(request):
    articles = Article.objects.all().order_by('date')
    data = {"header": "Homepage", 
            "what": "This website is used for article showing. write, read and engage!",
            "artshow": "Here are the latest articles:",
            "articles": articles
            }
    return render(request, 'homepage.html', context=data)

def about(request):
    header = "About us"
    staff = ['John Nicho', 'John Roger', 'Timothy Smith']
    director = {"name": "David Lee", "img": '/director.jpg'}
    address = ('20 W 34th St.', 'New York', 'NY 10001', 'USA')
    data = {"header": header, "staff": staff, "director": director, "address": address}
    return render(request, 'about.html', data)

def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, '../articles/article_list.html', {'articles': articles})

mysite/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login</title>
</head>
<body>
    <h1>Login</h1>
    <form class="form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <button type="submit">Login</button>
    </form>
</body>
</html>

mysite/accounts/templates/accounts/signup.html
{% extends "base_layout.html" %}

{% block title %}signup{% endblock %}

{% block content %}
<h1 class="smth">Sign up champ!</h1>
    <form class="form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="act_button">Sign up</button>
    </form>
{% endblock %}

mysite/articles/templates/articles/article_confirm_delete.html
{% extends "base_layout.html" %}
{% load static %}
{% block title %} {{ article.title }} {% endblock title %}
{% block content %}
<h1 class="smth">Are you sure?</h1>
<div class="article-confirm-delete">
<form class="form" method="POST">
    {% csrf_token %}
    <button type="submit" class="act_danger_button_2">Yes</button>
    <a href="{% url 'homepage' %}" class="act_button_2">Cancel</a>
</form>
</div>
{% endblock content %}

mysite/articles/templates/articles/article_create.html
{% extends "base_layout.html" %}
{% load static %}
{% block title %}Create article{% endblock title %}
{% block content %}
<h1 class="smth">Create Article</h1>
<div class="create_button">
    <form class="form" action="{% url 'articles:create'%}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="act_button">Create Article</button>
    </form>
</div>
{% endblock content %}

mysite/articles/templates/articles/article_form.html
{% extends "base_layout.html" %}
{% load static %}
{% block title %}Create or update article{% endblock title %}
{% block content %}
<h1 class="smth">Create or update article</h1>
<div class="create_button">
    <form class="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="act_button">Save</button>
    </form>
</div>
{% endblock content %}

mysite/articles/templates/articles/article_item.html
{% extends "base_layout.html" %}
{% block title %}{{ article.title }}{% endblock title %}
{% block content %}
    <div class="article-detail">
        <img src="{{ article.thumbnail.url }}" class="image">
        <h1>{{ article.title }}</h1>
        <p>{{ article.body }}</p>
        {% if user.is_authenticated and user.id == article.author.id %}
            <div>
                <a class="act_button" href="{% url 'articles:update' slug=article.slug %}">
                    Update
                </a>
                <a class="act_danger_button" href="{% url 'articles:delete' slug=article.slug %}">
                    Delete
                </a>
            </div>
        {% endif %}
    </div>
{% endblock content %}

mysite/articles/templates/articles/article_list.html
{% extends "base_layout.html" %}
{% block title %}Article List{% endblock title %}
{% block content %}
    <h1 class="smth">Article List</h1>
    <div class="articles">
        {% for element in articles %}
            <div class="article__item">
                <h2>
                    <a href="{% url 'articles:article-detail' slug=element.slug %}">
                        {{ element.title }}
                    </a>
                </h2>
                <p>
                        <!-- {{ element.body }} -->
                    {{ element.snippet }}
                </p>
                <time>
                    {{ element.date }}
                </time>
            </div>
        {% endfor %}
    </div>
    {% if user.is_authenticated %}
    <div class="article-create__link">
        <a href="{% url 'articles:create' %}" class="act_button">Create Article</a>
    </div>
    {% endif %}
{% endblock content %}

mysite/templates/about.html
{% extends "base_layout.html" %}

{% block title %}Homepage{% endblock %}

{% block content %}
<h1>{{ header }}</h1>
<p>Director: {{ director.name }}</p>
<p>Address: {{ address.0 }}, {{ address.1 }}, {{ address.2 }}, {{ address.3 }}</p>
<p>Staff: {{ staff.0 }}, {{ staff.1 }}, {{ staff.2 }}</p>
{% endblock %}

mysite/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}soft{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>
<body>
    <header>
        <div class="header_container">
            <div class="logo">
                <a href="{% url 'homepage' %}"></a>
                <img src="{% static 'css/softlogo.jpg' %}" alt="logo">
            </div>
            <input type="checkbox" id="burger-toggle">
            <label for="burger-toggle" class="burger">&#9776;</label>
            <nav class="nav-menu">
                <ul>
                    <li>
                        <a href="{% url 'homepage' %}">landing</a>
                    </li>
                    <li>
                        <a href="{% url 'homepage' %}">articles</a>
                    </li>
                    <li>
                        <a href="{% url 'about' %}">about us</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li>
                            <form action="{% url 'accounts:logout' %}" method="post" class="logout-form" >
                                {% csrf_token %}
                                <button type="submit" class="act_second_button">Logout</button>
                            </form>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li>
                            <a class="act_button_2" href="{% url 'accounts:signup' %}">Sign Up</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
</body>
</html>

mysite/templates/homepage.html
{% extends "base_layout.html" %}

{% block title %}Homepage{% endblock %}

{% block content %}
<h1>{{ header }}</h1>
<p>{{ what }}</p>
<h3>{{ artshow }}</h3>
<div class="articles">
    {% for element in articles %}
        <div class="article__item">
            <h2>
                <a href="{% url 'articles:article-detail' slug=element.slug %}">
                    {{ element.title }}
                </a>
            </h2>
            <p>
                    <!-- {{ element.body }} -->
                {{ element.snippet }}
            </p>
            <time>
                {{ element.date }}
            </time>
        </div>
    {% endfor %}
</div> 
{% endblock %}